#
# Create on 6/12/2018
#
# Author: Sylvia
#

"""
389. Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s, t = list(s), list(t)
        for char in s:
            t.remove(char)
        return t[0]